sudo: required
services:
        - docker

before_install:
        - docker build -t docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true docker-react npm run test

deploy:
        provider: elasticbeanstalk  # depending of the provider
        region: "us-west-2" # geographic area
        app: "docker-react"
        env: "Docker-react-env"
        bucket_name: ""
        bucket_path: "docker-react" # usually the same as the app name
        on:
                branch: master # only trigger deploy when new commit on master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
                secure: "$AWS_SECRET_KEY"

